# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3865220990b39876d7609c3fb24a129ffd2a09d4abd029aa028162aaf21d749e8425b1152bf0c4cc0cd9bbf21efaf95700397afd041126c038d771e334cd4b4d

test:
  secret_key_base: 04a552872648905faa0fa8e3a7181c46dd53dbec01cbb46e624233521be66130ab5f8ff07c375fe68decae667a62b4196110496df784cad84312a727f3b67f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
